api:
  base_url: https://localhost:12000/deposition
  orcid: 0000-0002-5109-8728
  country: United Kingdom

remote_archive:
  host: localhost
  user: onedep
  site_id: PDBE_DEV
  # host: pdb-002.ebi.ac.uk
  # user: w3_pdb05
  # site_id: PDBE_PROD
  # key_file: /home/onedep/.ssh/id_ebi

compare_rules:
  model.pdbx:
    method: cifdiff
    version: latest
    categories:
      - pdbx_contact_author
  model-upload.pdbx:
    method: cifdiff
    version: original
  model-upload-convert.pdbx:
    method: cifdiff
    version: latest
  mapfix-header-report.json:
    method: jsondiff
    version: latest
  structure-factors.pdbx:
    method: cifdiff
    version: latest
  chem-comp-assign.pdbx:
    method: cifdiff
    version: latest
  assembly-model.pdbx:
    method: cifdiff
    version: latest
  model-issues-report.json:
    method: jsondiff
    version: latest
  model-aux.pdbx:
    method: cifdiff
    version: latest

test_set:
  # D_8233000142:
  #   tasks:
  #     - upload:
  #       files:
  #         - model.pdbx
  #         - em-volume.map
  #         - em-half-volume.map
  #         - em-half-volume.map
  #         - img-emdb.jpg
  #     - compare_files:
  #       source: copy
  #       rules:
  #         - model.pdbx
  #         - model-upload.pdbx
  #         - model-upload-convert.pdbx
  #         - mapfix-header-report.json
  #     - submit
  #     - compare_files:
  #       source: copy
  #       rules:
  #         - model.pdbx
  D_8233000237:
    tasks:
      - submit
      - compare_files:
        source: copy
        rules:
          - model.pdbx
  D_8233000141:
    tasks:
      - compare_files:
        source: copy
        rules:
          - model.pdbx
  #     - upload:
  #       files:
  #         - model.pdbx
  #         - structure-factors.pdbx
  #     - compare_files:
  #       source: copy
  #       rules:
  #         - model.pdbx
  #         - structure-factors.pdbx
  #         - chem-comp-assign.pdbx
  #         - assembly-model.pdbx
  #     - submit
  #     - compare_files:
  #       source: copy
  #       rules:
  #         - model.pdbx
  # D_8233000197:
  #   tasks:
  #     - compare_files:
  #       source: wwpdb://deposit-ui/D_8233000142/
  #       rules:
  #         - model.pdbx
  #         - model-upload.pdbx 
  #         - model-upload-convert.pdbx
  #         - mapfix-header-report.json
  # D_1292123393:
  #   tasks:
  #     - upload:
  #       files:
  #         - model.pdbx
  #         - structure-factors.pdbx
  #     - compare_files:
  #       source: copy
  #       rules:
  #         - model.pdbx
  #         - structure-factors.pdbx
  #         - model-aux.pdbx
  #         - model-issues-report.json
  #     - submit
  #     - compare_files:
  #       source: copy
  #       rules:
  #         - model.pdbx
