remote_archive:
  host: localhost
  user: onedep
  site_id: PDBE_DEV

compare_rules:
  model.pdbx:
    method: cifdiff
    version: latest
    categories:
      - pdbx_contact_author
  model-upload.pdbx:
    method: cifdiff
    version: original
  model-upload-convert.pdbx:
    method: cifdiff
    version: latest
  mapfix-header-report.json:
    method: jsondiff
    version: latest
  structure-factors.pdbx:
    method: cifdiff
    version: latest
  chem-comp-assign.pdbx:
    method: cifdiff
    version: latest
  assembly-model.pdbx:
    method: cifdiff
    version: latest

test_set:
  D_8233000142:
    tasks:
      - upload:
        files:
          - model.pdbx
          - em-volume.map
          - em-half-volume.map
          - em-half-volume.map
          - img-emdb.jpg
      - compare_files:
        source: copy
        rules:
          - model.pdbx
          - model-upload.pdbx
          - model-upload-convert.pdbx
          - mapfix-header-report.json
      - submit
      - compare_files:
        source: copy
        rules:
          - model.pdbx
  D_8233000141:
    tasks:
      - upload:
        files:
          - model.pdbx
          - structure-factors.pdbx
      - compare_files:
        source: copy
        rules:
          - model.pdbx
          - structure-factors.pdbx
          - chem-comp-assign.pdbx
          - assembly-model.pdbx
      - submit
      - compare_files:
        source: copy
        rules:
          - model.pdbx
  D_8233000197:
    tasks:
      - compare_files:
        source: wwpdb://deposit-ui/D_8233000142/
        rules:
          - model.pdbx
          - model-upload.pdbx 
          - model-upload-convert.pdbx
          - mapfix-header-report.json
